let content=DBFLContent.load();let activePageId=null,activeNewsId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(message='Saved'){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
function persist(message){DBFLContent.save(content);renderLists();renderMedia();toast(message)}
function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
$$('.admin-nav button').forEach(button=>button.onclick=()=>{$$('.admin-nav button').forEach(b=>b.classList.remove('active'));button.classList.add('active');$$('.admin-panel').forEach(p=>p.classList.remove('active'));$('#panel-'+button.dataset.panel).classList.add('active');$('#panelTitle').textContent=button.textContent});
function renderLists(){
  $('#pageList').innerHTML=content.pages.map(p=>`<div class="content-item ${p.id===activePageId?'active':''}" data-page="${p.id}"><strong>${DBFLContent.escape(p.title)}</strong><span>/${DBFLContent.escape(p.slug)}</span><span class="status">${DBFLContent.escape(p.status)}</span></div>`).join('');
  $('#newsList').innerHTML=content.news.map(n=>`<div class="content-item ${n.id===activeNewsId?'active':''}" data-news="${n.id}"><strong>${DBFLContent.escape(n.title)}</strong><span>${DBFLContent.escape(n.date)} · ${DBFLContent.escape(n.category)}</span><span class="status">${DBFLContent.escape(n.status)}</span></div>`).join('');
  $$('[data-page]').forEach(el=>el.onclick=()=>editPage(el.dataset.page));$$('[data-news]').forEach(el=>el.onclick=()=>editNews(el.dataset.news));
}
function toolbar(editorId){return `<div class="toolbar"><button type="button" data-cmd="bold" title="Bold"><b>B</b></button><button type="button" data-cmd="italic" title="Italic"><i>I</i></button><button type="button" data-cmd="formatBlock" data-value="h2">H2</button><button type="button" data-cmd="formatBlock" data-value="p">P</button><button type="button" data-cmd="insertUnorderedList">List</button></div><div class="rich-editor" contenteditable="true" id="${editorId}"></div>`}
function bindToolbar(scope){scope.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);scope.querySelector('.rich-editor').focus()})}
function editPage(id){activePageId=id;const p=content.pages.find(x=>x.id===id);renderLists();$('#pageEditor').innerHTML=`<h2>${p.title?'Edit page':'New page'}</h2><div class="form-grid"><div class="field"><label>Page title</label><input id="pTitle" value="${DBFLContent.escape(p.title)}"></div><div class="field"><label>URL slug</label><input id="pSlug" value="${DBFLContent.escape(p.slug)}"></div><div class="field"><label>Eyebrow</label><input id="pEyebrow" value="${DBFLContent.escape(p.eyebrow)}"></div><div class="field"><label>Status</label><select id="pStatus"><option ${p.status==='published'?'selected':''}>published</option><option ${p.status==='draft'?'selected':''}>draft</option></select></div><div class="field full"><label>Introduction</label><textarea id="pIntro">${DBFLContent.escape(p.intro)}</textarea></div><div class="field full"><label>Page content</label>${toolbar('pBody')}</div></div><div class="actions"><button class="danger" id="deletePage">Delete</button><div><a class="secondary" href="page.html?slug=${encodeURIComponent(p.slug)}" target="_blank">Preview</a><button class="primary" id="savePage">Save page</button></div></div>`;$('#pBody').innerHTML=p.body;bindToolbar($('#pageEditor'));$('#pTitle').oninput=()=>{if(!$('#pSlug').dataset.touched)$('#pSlug').value=slugify($('#pTitle').value)};$('#pSlug').oninput=()=>$('#pSlug').dataset.touched='1';$('#savePage').onclick=()=>{Object.assign(p,{title:$('#pTitle').value.trim(),slug:slugify($('#pSlug').value),eyebrow:$('#pEyebrow').value.trim(),status:$('#pStatus').value,intro:$('#pIntro').value.trim(),body:$('#pBody').innerHTML,updated:new Date().toISOString().slice(0,10)});persist('Page saved')};$('#deletePage').onclick=()=>{if(confirm('Delete this page from the demo?')){content.pages=content.pages.filter(x=>x.id!==p.id);activePageId=null;$('#pageEditor').innerHTML='<div class="empty">Page deleted.</div>';persist('Page deleted')}}}
function editNews(id){activeNewsId=id;const n=content.news.find(x=>x.id===id);renderLists();$('#newsEditor').innerHTML=`<h2>${n.title?'Edit article':'New article'}</h2><div class="form-grid"><div class="field full"><label>Headline</label><input id="nTitle" value="${DBFLContent.escape(n.title)}"></div><div class="field"><label>Category</label><select id="nCategory"><option ${n.category==='News'?'selected':''}>News</option><option ${n.category==='Featured'?'selected':''}>Featured</option><option ${n.category==='Insights'?'selected':''}>Insights</option></select></div><div class="field"><label>Publish date</label><input id="nDate" type="date" value="${DBFLContent.escape(n.date)}"></div><div class="field"><label>Status</label><select id="nStatus"><option ${n.status==='published'?'selected':''}>published</option><option ${n.status==='draft'?'selected':''}>draft</option></select></div><div class="field"><label>Featured image URL</label><input id="nImage" value="${DBFLContent.escape(n.image||'')}"></div><div class="field full"><label>Summary</label><textarea id="nExcerpt">${DBFLContent.escape(n.excerpt)}</textarea></div><div class="field full"><label>Article</label><textarea id="nBody" style="min-height:220px">${DBFLContent.escape(n.body)}</textarea></div></div><div class="actions"><button class="danger" id="deleteNews">Delete</button><div><a class="secondary" href="article.html?id=${encodeURIComponent(n.id)}" target="_blank">Preview</a><button class="primary" id="saveNews">Save article</button></div></div>`;$('#saveNews').onclick=()=>{Object.assign(n,{title:$('#nTitle').value.trim(),category:$('#nCategory').value,date:$('#nDate').value,status:$('#nStatus').value,image:$('#nImage').value.trim(),excerpt:$('#nExcerpt').value.trim(),body:$('#nBody').value.trim()});persist('Article saved')};$('#deleteNews').onclick=()=>{if(confirm('Delete this article from the demo?')){content.news=content.news.filter(x=>x.id!==n.id);activeNewsId=null;$('#newsEditor').innerHTML='<div class="empty">Article deleted.</div>';persist('Article deleted')}}}
$('#newPage').onclick=()=>{const item={id:'page-'+Date.now(),slug:'new-page',status:'draft',title:'',eyebrow:'',intro:'',body:'<h2>New section</h2><p>Start writing here.</p>',updated:new Date().toISOString().slice(0,10)};content.pages.unshift(item);editPage(item.id)};
$('#newNews').onclick=()=>{const item={id:'news-'+Date.now(),title:'',category:'News',date:new Date().toISOString().slice(0,10),excerpt:'',body:'',image:'',status:'draft'};content.news.unshift(item);editNews(item.id)};
function renderMedia(){const built=[{name:'Founders 1987',src:'assets/images/founders-1987.jpg'},{name:'Rosslare Europort',src:'assets/images/hero-rosslare.jpg'},{name:'Ormond House',src:'assets/images/office-ormond-house.jpg'}];$('#mediaGrid').innerHTML=[...built,...content.media].map(m=>`<div class="media-item"><img src="${m.src}" alt=""><p>${DBFLContent.escape(m.name)}</p></div>`).join('')}
$('#mediaUpload').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>1500000){toast('Please choose an image under 1.5 MB');return}const reader=new FileReader();reader.onload=()=>{content.media.unshift({id:'media-'+Date.now(),name:file.name,src:reader.result});persist('Image uploaded')};reader.readAsDataURL(file)};
$('#resetDemo').onclick=()=>{if(confirm('Reset all demo edits?')){content=DBFLContent.reset();activePageId=activeNewsId=null;renderLists();renderMedia();toast('Demo reset')}};
renderLists();renderMedia();if(content.pages[0])editPage(content.pages[0].id);
